version: 2.1

jobs:
  test-and-build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "package.json"}}

      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: yarn install

      - save_cache:
              paths:
                    - node_modules
              key: deps-{{ checksum "package.json" }}

      - run: yarn test
      - run: yarn build
  
  audit:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - run: yarn audit

workflows:
  node-tests:
    jobs:
      - test-and-build
      - audit