version: 2.1
jobs:
  build-test:
    docker:
      # specify the version you desire here
      - image: circleci/node:12

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - run: yarn build
  security-audit:
    docker:
      - image: circleci/node:12
    steps:
      -checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: yarn install

      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: yarn audit

workflows:
  node-tests:
    jobs:
      - build-test
      - security-audit