export const FETCH_RESTAURANT_REQUEST = "restaurant/FETCH_RESTAURANT_REQUEST";
export const FETCH_RESTAURANT_SUCCESS = "restaurant/FETCH_RESTAURANT_SUCCESS";
export const FETCH_RESTAURANT_ERROR = "restaurant/FETCH_RESTAURANT_ERROR";
